chore: Update flake-schemas
`nix develop` starts failing after updating to Determinate Nix v3.17.0[1]:

  error: Flake 'git+file:///salon' does not have any schema that
  provides a default output for the role(s) nix-develop.

[1]: DeterminateSystems/nix-src#217